version: "{build}"
environment:
  matrix:

    - PYTHON: "C:\\Python27"
      TOX_ENV: "py27"

    - PYTHON: "C:\\Python27-x64"
      TOX_ENV: "py27"

    - PYTHON: "C:\\Python33"
      TOX_ENV: "py33"

    - PYTHON: "C:\\Python33-x64"
      TOX_ENV: "py33"

    - PYTHON: "C:\\Python34"
      TOX_ENV: "py34"

    - PYTHON: "C:\\Python34-x64"
      TOX_ENV: "py34"
      
init:
  - SET PATH=%PYTHON%;%PATH%
  - python -c "import sys, os;sys.stdout.write(str(sys.version) + os.linesep)"

install:
  - python -m pip install -U setuptools
  - python -m pip install -U pip
  - python -m pip install -U wheel
  - python -m pip install -U tox

build: false

test_script:
  - python -m tox -e %TOX_ENV%

after_test:
  - python setup.py bdist_wheel
  - ps: "ls dist"

artifacts:
  # Archive the generated wheel package in the ci.appveyor.com build report.
  - path: dist\*
